iLCSoft/ILDConfig

StandardConfig/lcgeo_current/ddsim_steer.py
Remove unnecessary CaloPreShowerSDAction, use MultiCollections inside ILD module if needed.
- Remove unnecessary CaloPreShowerSDAction.
- use MultiCollections inside ILD module if needed.
- use same "ddsim_steer.py" for all ILD modules without confusion.
=> Remove unnecessary CaloPreShowerSDAction, use MultiCollections inside ILD module if needed.

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- add paramerers for TPC endplate
- remove obsolete parameter DontEncodeSide in DDTPcDigiProcessor
- add TPC endplate parameters for  DDTPCDigiProcessor in bbuds_3evt_stdreco_dd4hep.xml
- remove obsolete parameter DontEncodeSide of DDTPcDigiProcessor
=> add TPC endplate to DDTPCDigi in stdreco

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- Updated Ecal calibration constants to reflect the ecal sensitive layer thickness change (+5%) in this ILD model
- Changed mip calibration constant in digitizer
- Changed ecal energy factors in digitizers
- Changed ECal mip scale in DDMarlinPandora accordingly
- Changed ECalToEmGeV in DDMarlinPandora to 1 to reflect what is done in the calibration procedure 
=> Ecal calibration updates for ILD_l4_v02 model

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_hybridecal.xml
- add stdreco file for ILD_ls5_v02 models w/ hybrid ecal
- merge collections from even and odd layers for Ecal barrel and endcap
before digitization
- requires LCTuple > v01-08  ( for correct collection parameters )
=> add stdreco file for ILD_ls5_v02 models w/ hybrid ecal

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- Fix ILD DDCellsAutomatonMV inputs.
- Added the inputs in the steering file from ILD_l4_v02 (VXD, SIT and SET) for the tracker detector elements.
=>  Fix ILD DDCellsAutomatonMV inputs.

StandardConfig/lcgeo_current/sdhcal_digi.xml
- The calibration constants of SDHCAL are re-calculated for ILD detector model.
=> Updated the calibration constants for SDHCAL.

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- Change ILD default central silicon tracking reconstruction.
- Mini-vectors are created connecting two hits in neighbouring vertex barrel layers.
- Cellular automaton is used to produce tracks from these mini-vectors which has been implemented into MarlinProcessor "DDCellsAutomatonMV".
- It shows better tracking efficiency for the ILD. ILD will use it together with MarlinProcessor "ExtrToSIT" as default ILDConfig to replace MarlonProcessor "SiliconTracking_MarlinTrk".
=>  Change ILD default central silicon tracking to use DDCellsAutomatonMV.

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- FCAL MIP thresholds updated (BCAL, LCAL, LHCAL) using ILD_l4_model and a 0.5 cut from MIP peak
=> FCAL MIP thresholds update

StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- switch back to using SiliconTracking rather than CellsAutomatonMV
- this fixes the degraded impact parameter resolution at 20 deg 
- reason is that no link is made from the VXD to the FTD and no SiTracks are created at this angle, which results in a large number of tracks having no VXD hits ...
=> switch back to using SiliconTracking

StandardConfig/production/CaloDigi/SiWEcalDigi.xml
- Added MergeCollection processors for hybrid ecal reconstruction : 
- Merge collection of odd/even ecal hits in a unique collection, one for the barrel, one for the endcap
- No effect on non-hybrid reconstruction, as the odd/even input collections do not exist in this case  
=> Hybrid ecal reconstruction

StandardConfig/lcgeo_current/lctuple.xml
- merged all ILD CalorimeterHit which include the information after ILD calorimeters reconstruction.
- added ILD CalorimeterHits into the LCTuple
- named as "scpox, scpoy, scpoz", sc... for SimCalorimeterHits after simulation
- named as "capox,capoy,capoz, catim", ca... for CalorimeterHits after reconstruction
=>  Added ILD CalorimeterHit information into LCTuple.

StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/Overlay/Overlay.xml
- Setup overlay config for each center of mass energy into processor groups : 
- added condition to execute a given overlay group by using a constant
- removed file names and expBG configuration from constants section
- set expBG values for 500 GeV to known values
- set expBG values for 250, 350 and 1000 GeV to -1 (not communicated yet)
Example to run at 500 GeV : 
```shell
Marlin --constant.RunOverlay500GeV=true \
--BgOverlayWW500GeV.InputFileNames=WWfile.slcio \
--BgOverlayWB500GeV.InputFileNames=WBfile.slcio \
--BgOverlayBW500GeV.InputFileNames=BWfile.slcio \
--BgOverlayBB500GeV.InputFileNames=BBfile.slcio \
--PairBgOverlay500GeV.InputFileNames=Pairfile.slcio \
./ProductionSteeringFiles/MarlinStdReco_ILD_l5_o1_v02.xml
```
=> Overlay config updates

StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml, StandardConfig/production/CaloDigi/MuonDigi.xml, StandardConfig/production/ParticleFlow/PandoraPFA.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o1_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o2_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o1_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o2_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o3_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o4_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o1_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o2_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o1_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o2_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o3_v02.xml, StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o4_v02.xml
- Fixed missing calibration constants in all calibration files (all models)
- missing calibration constant for muon
- missing calibration constant for soft comp weights
- Fixed missing reference to calibration constants in PandoraPFA processor
- Updated calibration constants for all ILD_l/s5 variants
- Re-generated production steering files
=> Calibration updates

StandardConfig/production/HighLevelReco/HighLevelReco.xml
- Fixed collection name for distilled PFO creation (was PandoraPFOsWithoutLeptons instead of PandoraPFOs)
=> Distilled PFO : wrong input collection

StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml, StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/ParticleFlow/PandoraPFA.xml
- DST output 
- Drop the PandoraPFANewStartVertices collection
- REC output
- Drop sim calorimeter hit collection depending on the hybrid technology in use.
- E.g : drop ScECal and SDHCal hits if we use SiECal and AHCal in the reconstruction
- Marlin Pandora settings
- Explicit the settings for vertex collection and vertex algorithm name
=> DST and REC file updates

StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- The SDHCAL parameters for linear energy function and hadronic energy related parameters
in PandoraPFA are updated based the new calibration for ILD_l5_o2_v02 and ILD_l5_o4_v02. 
=> Updated calibration parameters of SDHCAL

StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml, StandardConfig/production/HighLevelReco/HighLevelReco.xml, StandardConfig/production/MarlinStdReco.xml
- Changed MCParticlesSkimmed to MCParticle collection in DST
- Added 3 more relation collections to DST :  MCTruthRecoLink, MCTruthClusterLink and ClusterMCTruthLink
- Added two new constants for sim calo hit collections (to deal with hybrid models)
- Corrected wrong input collection names in MCThruthLinker processor : SimCaloHitCollections and SimCalorimeterHitRelationNames
=> Dst and relations collections

StandardConfig/production/Tracking/TrackingReco.xml
- relax MinChi2ProbForSiliconTracks in FullLDCTracking
- should increase tracking efficiency in forward region
- otherwise found forward tracks w/ large chi2/ndf are droped
=> relax MinChi2ProbForSiliconTracks in FullLDCTracking

StandardConfig/production/CaloDigi/FcalDigi.xml, StandardConfig/production/HighLevelReco/BeamCalReco.xml, StandardConfig/production/MarlinStdReco.xml
- BeamCal calibration:
- moved calibration constant of BeamCal in a Marlin constant
- use Marlin constant in the BeamCal digitizer and the BeamCalClusterReco
- energy calibration constant updated to 79.6 (old was 72)
=> BeamCal calibration update

.travis-ci.d/test.sh, StandardConfig/production/MarlinStdReco.xml
- TravisCI
- Restrict simulation and reconstruction to ILD_l5_o1_v02 to avoid timeout in TravisCI
- MarlinStdReco.xml
- Changed default `DetectorModel` constant to none causing error if user don't specify it
=> Default model fix

StandardConfig/production/Documentation/HowToRunBgOverlay.md
The sigmaZ values was given in cm unit. ( 1 order value ). Also, the sigmaZ value is added in the command line argument of signal simulation.
- Background overlay documentation :
- Fixed wrong sigmaZ value (cm to mm)
- Added sigmaZ value to ddsim command line of signal simulation
=> Correct sigmaZValue

.travis-ci.d/test.sh, .travis.yml, README.md, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Config/Parameters1000GeV.xml, StandardConfig/production/Config/Parameters250GeV.xml, StandardConfig/production/Config/Parameters350GeV.xml, StandardConfig/production/Config/Parameters500GeV.xml, StandardConfig/production/Config/ParametersUnknownGeV.xml, StandardConfig/production/Documentation/HowToRunBgOverlay.md, StandardConfig/production/Documentation/ProductionSettings.md, StandardConfig/production/HighLevelReco/HighLevelReco.xml, StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/Overlay/OverlayParameters1000GeV.xml, StandardConfig/production/Overlay/OverlayParameters250GeV.xml, StandardConfig/production/Overlay/OverlayParameters350GeV.xml, StandardConfig/production/Overlay/OverlayParameters500GeV.xml, StandardConfig/production/Overlay/OverlayParametersUnknownGeV.xml, StandardConfig/production/README.md
- Overlay settings moved to Config directory
- Created new constants, energy dependant, for beam size parameters
- High level reco: vertexing
- Get beam size parameters depending on the CMS energy
- Use beamspot smearing only if a CMS energy is specified with `--constant.CMSEnergy=...`
- TravisCI test
- Run simulation for ILD_l/s5_v02 and reconstruction for ILD_l/s5_o1/o2_v02
- Switch off BeamCalReco to avoid TravisCI timeout and test failure
- Fixed wrong HCal sim calo hit collection names in Calibration file for ILD_s5_o2_v02 model
=> Beam size parameters update

StandardConfig/production/MarlinStdReco.xml
- PfoAnalysis processor config :
- Switch off the calibration details, saving time and nasty printouts in log files for production
=> Calibration details in PfoAnalysis processor

StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v03.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v04.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v05.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v06.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v03.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v04.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v05.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v06.xml
- Added symbolic link for calibration constants of v03,4,5,6 models pointing on the v02 model ones
=> Calibration constants for v03, v04, v05, v06 models

StandardConfig/production/ddsim_steer.py
- Do not apply senDetFilter for TPC.
- because the TPC sensitive driver need every G4Step information to find out when the track cross the boundary. 
fixes https://github.com/iLCSoft/lcgeo/issues/227
=>  Do not apply senDetFilter for TPC.

StandardConfig/production/Documentation/ProductionSettings.md
Missing 1 TeV vertex parameters, reported by Mikael and agreeded at the ILD Coftware Conveners meeting on 4 July, were added. In addition, ILC machine parameter names corresponding to the vertex parameters are included .
=> Include 1TeV vertex parameters

StandardConfig/production/MarlinStdRecoViewer.xml
- add missing (Sim)CalorimterHit collections to the event display steering file MarlinStdRecoViewer.xml
=> add missing calo hit cols to MarlinStdRecoViewer.xml

StandardConfig/production/Config/Parameters250GeV.xml, StandardConfig/production/Documentation/ProductionSettings.md
- Added 250 GeV beamspot parameters:
- aa_lowpt background parameters for overlay processor
- Beam spot constraints for LCFIPlus  
=> 250 GeV beam-spot

StandardConfig/production/ddsim_steer.py
- bug fix for decay of 'stable' particles (pi+-,mu+-,K+- and K0L)
- workaround for https://github.com/AIDASoft/DD4hep/issues/513
=> set physics.decays = False (fixes DD4hep#513)

StandardConfig/production/Tracking/TrackingReco.xml
…re bin, and to use simple AttachHitToTrack for merging split track segments.
- Improve steering parameters for SiliconTracking ( requires https://github.com/iLCSoft/MarlinTrkProcessors/pull/39)
- to use simple updated triplets searching core bin,
- "True" needed for low momentum curving tracks.
- to use simple AttachHitToTrack for merging split track segments.
- allow VXDLayerCombinations "3 2 1  3 2 0  2 1 0" searching for ~20 degree tacks and merging (True)
- "True" needed for merging split track segments found in both VXD (above) and FTD detectors.  
- Both work fine w/o background overlay and w/ benchmark background overlay.
- VXDLayerCombinations "3 2 1  3 2 0  2 1 0" are required.
=> Improved SiliconTracking performance

StandardConfig/production/CaloDigi/SiWEcalDigi.xml, StandardConfig/production/HighLevelReco/HighLevelReco.xml
- turn off gaps between ECAL modules in the BruteForceEcalGapFiller
- run the photonCorrectionProcessor to correct energy of photon PFOs after Pandora
this new config should be used only for ILD_l5_o1_v02 models (and others with the same ECAL structure)
=> Photon energy corrections

StandardConfig/production/Documentation/DSTContent.md, StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/Tracking/TrackingReco.xml
- Added two processors for track-refitting:
- `MyRefitProcessorKaon`: refit `MarlinTrkTracks` tracks with a kaon mass hypothesis
- `MyRefitProcessorProton`: refit `MarlinTrkTracks` tracks with a proton mass hypothesis
- Updated DST content documentation
- DSTOutputProcessor:
- Keep the `MyRefitProcessorKaon` and `MyRefitProcessorProton` new track collections but drop the relation collections created by the corresponding processors
=> Track refit processors

StandardConfig/production/CaloDigi/MuonDigi.xml
- Fixed wrong parameter name MUONThreshold -> MuonThreshold
- Set parameter MuonTimeThreshold to the same value as MuonThreshold
- Set threshold value to 0.025 for consistency with 500 GeV MC production
TODO:
=> Muon digi update

StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/MarlinStdReco.xml
- Updated calibration constants for models:
+ `ILD_l5_o1_v02`
+ `ILD_l5_o3_v02`
+ `ILD_s5_o1_v02`
+ `ILD_s5_o3_v02`
- Set `PfoAnalysis.LookForQuarksWithMotherZ` to 2 to deal with new uds generator samples
- **The photon energy correction has not been re-tuned for ILD_s5_v02 variants. To get a proper photon energy correction, you would have to re-run it with the small model**
=> Calibration update (v02-01)

StandardConfig/production/ParticleFlow/PandoraPFA.xml
- `ParticleFlow` settings:
- Set Yoke barrel normal direction vector to (0,1,0).
- Goes with https://github.com/iLCSoft/lcgeo/pull/241
Fixes #88
=> Muon reconstruction fix

StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- Updated dEdX smearing factor:
- ILD large models: 0.029
- ILD small models: 0.036 based on large model value
=> dEdX smearing factor update

StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml
- Adjusted ECal calibration constants for `ILD_l5_o1_v02` and `ILD_l5_o2_v02`:
- Barrel -0.58% 
- Endcap +0.52%
- Ring -0.5%
See https://agenda.linearcollider.org/event/8498/contributions/45417/attachments/35432/54933/photonCheck_v0201.pdf for details
=> ECal calibration ajustement

StandardConfig/production/PandoraSettings/PandoraSettingsDefault.xml, StandardConfig/production/PandoraSettings/PandoraSettingsDefault_sdhcal.xml
- Updated PandoraSettingsDefault.xml and PandoraSettingsDefault_sdhcal.xml
- maximum cluster size in Yoke changed from 30 to 100 hits
- changed MinTrackCandidateEnergy from 7 GeV to 4 GeV in muon reconstruction
=> Muon issue: Pandora settings fix

.travis.yml, StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml, StandardConfig/production/CaloDigi/ScEcalDigi.xml, StandardConfig/production/HighLevelReco/HighLevelReco.xml
- This code is now ready for review.
- this is (should be) consistent with update of DDStripSplitter changes in https://github.com/iLCSoft/MarlinReco/pull/74
- set up digi/reco/strip splitting for ScECAL
- updated ScECAL calibration
=> Set up the ScECAL reconstruction

StandardConfig/production/MarlinStdReco.xml
- Set LCIO compression level explicitly to 6 for REC and DST output files
=> LCIO output compression

StandardConfig/production/MarlinStdRecoMiniDST.xml, StandardConfig/production/run_standard_workflow.sh
- Introduce the `lcgeo_DIR` constant into the mini-DST workflow. This makes it possible to set this value from the outside without having to rely on an envrionment variable being resolved automatically.
The `v02-02-02` version does not work inside a key4hep installation, because apparently environment variables are not automatically resolved. This could be due to a number of reasons, as quite a few packages are involved. Introducing the `lcgeo_DIR` constant (similar to `MarlinStdReco.xml`) allows to explicitly set this from the outside. 
iLCSoft `v02-02-02` still runs without `--constant.lcgeo_DIR=$lcgeo_DIR`.
=> Make the miniDST workflow more robust

StandardConfig/production/HighLevelReco/HighLevelReco.xml
- All steering parameters of `TOFEstimators` are explicitly specified in the steering file w/o any modification to the behaviour
Update time of flight processor steering parameters for consistency with a current version. Number of layers parameter has been renamed. New steering parameters are explicitly specified for clarity.
=> Explicitly specify all new TOFEstimator steering parameters to avoid confusion with the old version usage

StandardConfig/production/HighLevelReco/HighLevelReco.xml
- Added TrackLength processor in the HighLevelReco chain.
This is dependency PR to make production steering file compatible with migrating TrackLength code from TOFEstimators to separate processor ( [PR 104)](https://github.com/iLCSoft/MarlinReco/pull/104).
There have been no changes to TOFEstimators steering parameters, so we need only to add the new TrackLength processor into the reconstruction chain
=> Update steering file to be compatible with migrated track length code

StandardConfig/production/Calibration/Calibration_ILD_l2_v02.xml, StandardConfig/production/Calibration/Calibration_ILD_s2_v02.xml
- Add Calibration files to be able to run standard Marlin reconstruction on ILD simulation with Videau geometry.
- For this first pass, files are only link to current ILD option 2 model from hybrid TESLA geometry.
- Verification that Marlin runs on both small and large ILD Videau geometry have been done.
=> Add Calibration link for Marlin Reconstruction ILD option 2 with Videau geometry

StandardConfig/production/HighLevelReco/HighLevelReco_SiILD.xml, StandardConfig/production/ParticleFlow/PandoraPFA_SiILD.xml, StandardConfig/production/README.md, StandardConfig/production/Tracking/ConformalTracking_SiILD.xml, StandardConfig/production/Tracking/TrackingDigi_SiILD.xml
- Digitisation including the hits from CLIC-like outer tracker and changes for the FTD, allowing for further use of the Conformal Tracking
- Conformal tracking with input collections from the new ILD_l5_v09 model, parameters setup as in CLIC config.
This is still work in progress, requires e.g. some further parameter tuning, but I was suggested to share these files (which of course makes a lot of sense).
=> Digitisation and tracking steering files for the new ILD_l5_v09 model

StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/ParticleFlow/PandoraPFAPerfect.xml
This changes allows to run perfect PandoraPFA using MCtruth. To run perfectPFA, a relation between Tracks and true MCParticles has to be provided. This relation is produced by the RecoMCTruthLinker which is run after. 
When using perfectPFA, one needs the RecoMCTruthLinker to be run before Pandora for the track-truth association and after for the cluster-truth and reco-truth association.
Add option to run different PFA type in Standard Reco and add an xml file to run perfect PandoraPFA based on MC truth.
=> Allows to run standard reconstruction with perfect PFA

.github/workflows/key4hep.yml
- Add CI workflows based on key4hep releases and nightlies that run the typical 3 ttbar events simulation & full reconstruction for
- LCIO inputs / outputs using Marlin: `MarlinStdReco.xml`, `MarlinStdRecoLCTuple.xml` and `MarlinStdRecoMiniDST.xml`
- EDM4hep inputs / outputs using Gaudi: `ILDReconstruction.py`
- The setup currently only uses the `ILD_l5_o1_v02` geometry, but more geometries can be added
Especially the Gaudi / MarlinWrapper based workflows are still a bit flaky because the event contents, including ParticleID meta information is not always the same so some randomness is in play and this still needs a bit more work to stabilize / homogenize the outputs better.
=> Add CI workflows for running the 3 ttbar events tests

.github/workflows/key4hep.yml, StandardConfig/production/Calibration/Calibration_ILD_FCCee_v01.cfg, StandardConfig/production/Calibration/Calibration_ILD_FCCee_v02.cfg, StandardConfig/production/ILDReconstruction.py
- minimal requirements for reco with ILD_FCCee_v01/2 models satisfied
=> Enable reco for ILD_FCCee_v01/2

StandardConfig/production/BgOverlay/BgOverlay.py, StandardConfig/production/CaloDigi/AHcalDigi.py, StandardConfig/production/CaloDigi/FcalDigi.py, StandardConfig/production/CaloDigi/MuonDigi.py, StandardConfig/production/CaloDigi/SDHcalDigi.py, StandardConfig/production/CaloDigi/ScEcalDigi.py, StandardConfig/production/CaloDigi/SiWEcalDigi.py, StandardConfig/production/HighLevelReco/BeamCalReco.py, StandardConfig/production/HighLevelReco/HighLevelReco.py, StandardConfig/production/ILDReconstruction.py, StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/ParticleFlow/PandoraPFA.py, StandardConfig/production/ParticleFlow/PandoraPFAPerfect.py, StandardConfig/production/Tracking/TrackingDigi.py, StandardConfig/production/Tracking/TrackingDigi_FCCeeMDI.py, StandardConfig/production/Tracking/TrackingReco.py, StandardConfig/production/Tracking/TrackingReco_FCCeeMDI.py
This allows the global output setting of Gaudi to actually apply to them. Otherwise it's not possible to set this globally.
- Remove all `OutputLevel` settings from the wrapped Marlin processors in `ILDReconstruction.py` and components.
See also key4hep/k4MarlinWrapper#205 for the original source of this configuration.
=> Remove all OutputLevel configurations from procesors

StandardConfig/production/ILDReconstruction.py
- Make sure that the `py_utils` import works as expected by setting PYTHONPATH on the fly accordingly.
Fixes #154
=> Make sure that py_utils can be imported

StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v09.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_l5_v11.cfg, StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.cfg, StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.cfg, StandardConfig/production/ILDReconstruction.py, StandardConfig/production/py_utils.py
- Introduce a `DropCollectionsCalibrationREC` for all the `CONSTANTS` configurations to free **`AdditionalDropCollectionsREC`** for user defined collections that should be dropped.
- Introduce `get_drop_collections` function that does the appropriate merging.
Fixes #153
=> Introduce new constant to allow users to drop more collections

.github/workflows/key4hep.yml
- Switch to Ubuntu24 for the CI workflows that test the FCCee models
=> Switch to Ubuntu 24 nightlies for FCC models

StandardConfig/production/MarlinStdReco.xml, StandardConfig/production/MarlinStdRecoLCTuple.xml
- Set the default verbosity to `MESSAGE` for `MarlinStdReco.xml` and `MarlinStdRecoLCTuple.xml`
=> Reduce the default verbosity to not flood logs

StandardConfig/production/Tracking/TrackingReco_FCCeeMDI.py, StandardConfig/production/py_utils.py
- fixes: wrong position of fmt off/on statements render them ineffective
- refactors the `ConformalTrackingV2` processor configuration in `TrackingReco_FCCeeMDI.py`
The previous manual string-list definition for the `Steps` parameter was unwieldy, especially with autoformatting that spread each item across a new line. This change introduces a new utility function, `encode_CT_steps_dict_to_legacy_list` in `py_utils.py`, allowing the conformal tracking steps to be defined using a structured Python dictionary.
This significantly improves readability and maintainability by:
- Presenting the configuration in a more intuitive, nested dictionary format.
- Reducing the number of lines occupied by the configuration, particularly after autoformatting.
This is a refactoring effort …
=> Refactor ConformalTrackingV2 Configuration
