iLCSoft/ILDConfig

- StandardConfig/lcgeo_current/README.md
- StandardConfig/lcgeo_current/ddsim_steer.py
- StandardConfig/lcgeo_current/ddsim_steer_default.py
-  update ddsim_steer.py based on complete default steering file
- update the field propagation parameters
should prevent Geant4 crashes with field propagation errors ...
- add ddsim_steer_default.py with ddsim default values for all parameters
- use diff to ddsim_steer.py as reference for changed values
> Improve ddsim steer

- StandardConfig/lcgeo_current/sdhcal_digi.xml
- Added example of steering file for sdhcal digitizer
> Steering file for sdhcal digitizer

- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep_stripSIT.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_hybridecal.xml
- bug fix for RecoMCTruthLinker information in REC/DST files
- replace PandoraClustersHack w/ PandoraClusters
in all relevant steering files
> fix RecoMCTruthLinker config (PandoraClusters)

- StandardConfig/lcgeo_current/PandoraSettingsBasic.xml
- StandardConfig/lcgeo_current/PandoraSettingsDefault.xml
- StandardConfig/lcgeo_current/PandoraSettingsMuon.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPFA.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhoton.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhotonNeutronK0L.xml
- StandardConfig/lcgeo_current/PandoraSettingsPhotonTraining.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- StandardConfig/lcgeo_current/calibration_report/SoftwareCompensationCalibration_ILD_l4_v02.txt
- StandardConfig/lcgeo_current/calibration_report/calibration_ILD_l4_v02.xml
- new calibration and software compensation for ILD_l4_v02
- Updated calibration constants in main Marlin file: bbudsc_3evt_stdreco_dd4hep.xml
- Updated software compensation parameters in all Pandora settings files
- Added calibration report files for easy comparison with incoming re-calibrations
> [WIP] Calibration update

- StandardConfig/lcgeo_current/PandoraSettingsBasic.xml
- StandardConfig/lcgeo_current/PandoraSettingsDefault.xml
- StandardConfig/lcgeo_current/PandoraSettingsMuon.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPFA.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhoton.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhotonNeutronK0L.xml
- StandardConfig/lcgeo_current/PandoraSettingsPhotonTraining.xml
- StandardConfig/lcgeo_current/calibration_report/SoftwareCompensationCalibration_ILD_l4_v02.txt
- Software compensation weights re-tuned
> Software compensation weights updated

- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- update bbudsc_3evt_stdreco_dd4hep.xml:
- reduce InitialTrackErrorOmega for FullLDCTracking
- update doc for bbudsc_3evt_stdreco_dd4hep.xml
- use ILD_l4_v02 as default model
> Fix config

- StandardConfig/lcgeo_current/PandoraSettingsDefault_sdhcal.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_sdhcal.xml
- Updated sdhcal Pandora settings file for SDHCAL reconstruction
- Updated sdhcal Marlin steering file for SDHCAL reconstruction
> [WIP] Updates on sdhcal reco

- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- set ForceSiTPCMerging=1 in FillLDCTracking
> set ForceSiTPCMerging=1 in FillLDCTracking

- StandardConfig/lcgeo_current/PandoraSettingsBasic.xml
- StandardConfig/lcgeo_current/PandoraSettingsDefault.xml
- StandardConfig/lcgeo_current/PandoraSettingsDefault_sdhcal.xml
- StandardConfig/lcgeo_current/PandoraSettingsMuon.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPFA.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhoton.xml
- StandardConfig/lcgeo_current/PandoraSettingsPerfectPhotonNeutronK0L.xml
- StandardConfig/lcgeo_current/PandoraSettingsPhotonTraining.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_sdhcal.xml
- Removed software compensation weights from Pandora settings file
- Added software compensation input parameters in DDMarlinPandora processor : 
- SoftwareCompensationWeights : the sc weights
- SoftwareCompensationEnergyDensityBins : the energy density bins
- FinalEnergyDensityBin : the final energy density value
> Externalize Pandora software compensation parameters

- StandardConfig/production/GenerateSteeringFiles.py
- StandardConfig/production/README.md
- Fixed a bug in GenerateSteeringFiles.py (detectorModels arg option)
- Updated README.md
> Production config updates

- StandardConfig/production/Gear/gear_ILD_l5_o1_v02.xml
- StandardConfig/production/Gear/gear_ILD_l5_o2_v02.xml
- StandardConfig/production/Gear/gear_ILD_l5_o3_v02.xml
- StandardConfig/production/Gear/gear_ILD_l5_o4_v02.xml
- StandardConfig/production/Gear/gear_ILD_s5_o1_v02.xml
- StandardConfig/production/Gear/gear_ILD_s5_o2_v02.xml
- StandardConfig/production/Gear/gear_ILD_s5_o3_v02.xml
- StandardConfig/production/Gear/gear_ILD_s5_o4_v02.xml
- StandardConfig/production/GenerateSteeringFiles.py
- StandardConfig/production/MarlinStdReco.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o4_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o4_v02.xml
- Added Gear files for current detector models
- New directory *ProductionSteeringFiles* containing Marlin XML generated files for production (generated from v01-19-05-pre04 from cvmfs)
> Generated Gear and Marlin steering files

- StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml
- Calibration for ILD_l4_v02 (from LCWS) updated in lcgeo_current directory
> Calibration ILD_l4_v02 (LCWS)

- StandardConfig/production/Tracking/TrackingDigi.xml
- Production directory : 
- re-added missing SETPlanarDigiProcessor processor in TrackingDigi.xml
> Missing SETPlanarDigiProcessor processor

- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o4_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o4_v02.xml
- Updated production steering files (missing SET processor)
> Production steering file updates

- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_l5_o4_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s4_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o1_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o2_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o3_v02.xml
- StandardConfig/production/ProductionSteeringFiles/MarlinStdReco_ILD_s5_o4_v02.xml
- Re-generate production steering files, with OutputSteeringFile parameter empty
> Production script re-generation

- StandardConfig/production/CaloDigi/MuonDigi.xml
- Switch from SimpleMuonDigi to DDSimpleMuonDigi processor. 
- Updated steering file configuration to run DDSimpleMuonDigi (detector names from lcgeo)
> Switch to DDSimpleMuonDigi

- doc/ReleaseNotes.md
- update release notes for v01-19-05-p01
> update release notes for v01-19-05-p01

- StandardConfig/production/MarlinStdReco.xml
- Removed overlay parameters runOverlay and NSkipEventsRandom (removed from processor)
> [WIP] Overlay parameters update

- StandardConfig/production/ddsim_steer.py
- change to default parameters for field stepping in Geant4
- test if this works for ILD and improves simulation speed (see: #48)
> change to default parameters for field stepping

- .travis-ci.d/test.sh
- .travis.yml
- Setup Travis CI 
- DDSim 3 events test
- ILD_l5_v02
- ILD_s5_v02
- Marlin 3 events test (no bg)
- ILD_l5_o1_v02
- ILD_l5_o2_v02
- ILD_s5_o1_v02
- ILD_s5_o2_v02
> [WIP] Travis CI setup

- StandardConfig/production/HighLevelReco/HighLevelReco.xml
- Thank you for writing the text to appear in the release notes. It will show up
exactly as it appears between the two bold lines
- ...
> Some settings relevant to vertexing with LCFIPlus changed or explicitly stated.

- StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- Updated calibration constants for small ILD models with SDHCAL by re-calibration
> Updated calibration constants for SDHCAL

- .travis.yml
- Removed Coverity scan from CRON build
> Remove coverity scan

- StandardConfig/production/ddsim_steer.py
-revert the field stepper back to HelixSimpleRunge
- observe degraded tracking performance w/ G4ClassicalRK4
> revert the field stepper back to HelixSimpleRunge

- StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- StandardConfig/production/Tracking/TrackingReco.xml
- Compute_dEdxProcessor config
- Updated settings
- Moved dedx smearing factor to calibration as it depends on large/small detector flavor
> Compute_dEdXProcessor updates 

- StandardConfig/production/Calibration/Calibration_ILD_l4_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l4_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s4_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s4_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- StandardConfig/production/Documentation/DSTContent.md
- StandardConfig/production/MarlinStdReco.xml
- StandardConfig/production/ParticleFlow/PandoraPFA.xml
- StandardConfig/production/README.md
- PandoraPFA settings:
- Switch on usage of dd4hep B field
- Correct missing relation calo hit collections
- BeamCalReco settings
- Switch on BeamCalReco by default
- Updated documentation
> [WIP] Switch on features

- StandardConfig/production/ParticleFlow/PandoraPFA.xml
- PandoraPFA.xml
- switch back to fixed BField values read from steering file instead of DD4hep B field
> Pandora BField regression

- StandardConfig/production/Calibration/Calibration_ILD_l5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_l5_o4_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o1_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o2_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o3_v02.xml
- StandardConfig/production/Calibration/Calibration_ILD_s5_o4_v02.xml
- StandardConfig/production/Config/Parameters1000GeV.xml
- StandardConfig/production/Config/Parameters250GeV.xml
- StandardConfig/production/Config/Parameters350GeV.xml
- StandardConfig/production/Config/Parameters500GeV.xml
- StandardConfig/production/HighLevelReco/BeamCalBackground/BeamCalBackground-EUnknown-B3.5-RealisticNominalAntiDid.root
- StandardConfig/production/HighLevelReco/BeamCalBackground/BeamCalBackground-EUnknown-B4.0-RealisticNominalAntiDid.root
- StandardConfig/production/MarlinStdReco.xml
- StandardConfig/production/MarlinStdRecoBeamCalPreMap.xml
- Added BeamCal maps for BeamReco at 1 TeV (l5 and s5)
- Added missing BeamCal for BeamReco at 500 GeV for s5 model (4T)
- Filled numbers for 1 TeV
- Expected background rates for gg_lowpt overlay (BB, BW, WB and WW)
- Beam size for LCFIPlus vertex fit constraint (x, y and z)
- Filled numbers for 250 GeV 
- Beam size for LCFIPlus vertex fit constraint (x, y **but not z**), from [ILC new 250 GeV baseline](https://arxiv.org/pdf/1711.00568.pdf)
- Filled numbers for 350 GeV 
- Beam size for LCFIPlus vertex fit constraint (x, y **but not z**), taken from [ILC TDR](https://arxiv.org/ftp/arxiv/papers/1306/1306.6327.pdf)
- Changed numbers for 500 GeV
- Beam size for LCFIPlus vertex fit constraint (x, y), taken from [ILC TDR](https://arxiv.org/ftp/arxiv/papers/1306/1306.6327.pdf) …
> BeamCal maps for 1 Tev

- StandardConfig/production/Tracking/TrackingDigi.xml
- change SIT resolution from 7 micron to 5 micron
- (correct number according to M.Winter)
> change SIT resolution from 7mu to 5mu

- StandardConfig/production/ddsim_steer.py
- make compatible w/ DD4hep 
- replace SystemOfUnits w/ g4units in ddsim
> replace SystemOfUnits w/ g4units in ddsim

- StandardConfig/production/HighLevelReco/BeamCalReco.xml
- Added BeamCal background map for 250 GeV, nominal Anti-DID only
- Changed BeamCalClusterReco background parametrization to Gaussian
> Beamcal 250 update

- StandardConfig/production/HighLevelReco/HighLevelReco.xml
- PIDLikelihood parameters
- Updated dEdX parameters
Fixes #93 
TODO:
> [WIP] PIDLikelihood: new dEdX parameters 

- StandardConfig/production/Config/Parameters250GeV.xml
- Set expected bkg parameters for 250 GeV config
> Overlay parameters 205 GeV

- StandardConfig/production/HighLevelReco/HighLevelReco.xml
- HLR: Added TOF processor for 100 ps time resolution
> TOF 100 ps

- StandardConfig/production/RootMacros/draw_etot.C
- StandardConfig/production/RootMacros/draw_simhits.C
- StandardConfig/production/RootMacros/funs.C
- Macros used in the tutorial work again
> Fix macros that are used in tutorials

- StandardConfig/production/HighLevelReco/HighLevelReco.xml
- add parameters to define photon PFO direction correction
> photon PFO direction correction

- StandardConfig/production/MarlinStdReco.xml
- Keep MCParticlesSkimmed instead of MCParticle in DST output
> MCParticlesSkimmed in DST output

- StandardConfig/production/HighLevelReco/HighLevelReco.xml
- Updated dE/dx parameters in Likelihood PID processor
> Likelihood processor parameters update (dE/dx)

- StandardConfig/production/README_mini-DST.md
- StandardConfig/production/mini-DST-maker.xml
- added mini-DST-maker.xml: for the mini-DST file production
- README_mini-DST.md: readme file for mini-DST-maker.xml
> added mini-DST-maker.xml and its README

- StandardConfig/production/README.md
- Update  the README to use the `v02-02-02` release
> Update README to use v02-02-02

- StandardConfig/production/ParticleFlow/PandoraPFA.xml
- Corrected Collection Name Track-MCTruth Link
> Corrected Collection Name Track-MCTruth Link

- StandardConfig/production/README.md
- Update the README to point to the `v02-03-03` release
- Add brief description of how to get an ILDConfig that is consistent with the release
> Update the README to use the latest release

- .github/workflows/key4hep.yml
- Run the CI workflows on a daily schedule to detect accidental upstream breakages
> Run the CI workflows on a daily schedule
